### ISSUE TITLE
Problems and ideas for solving them

### ISSUE THREAD

**Issue by engtomas** [NKoonen/vatchecker#3] opened 2020-11-26 09:51 UTC
Unfortunately i'm not a good PHP coder, just a newbie, but i think I can help.

I readed all the posts and a possible way to solve them is:

1. Since the VIES Client will have at least two groups, one is the VAT free group and the other is the Standard PS Client (non VAT free) group, you can associate the invoice address of the client to the use of one of this groups.
2. Everytime a client creates or edits an invoice address,  vatchecker will verify in the VIES system and assigns the correct group to that address
3. When a client chooses one address over another, vatchecker will activates the corresponding group, and with it the VAT policy (free or not) changing in real time prices and totals of the display and invoice.
4. Vatchecker would need also a checkbox somewhere that allows webmaster to disable the VAT free group to a specific client that proved not to be the real company mentioned at the address, and that would over-ride the vatchecker group associating procedure of editing and creating address. 
5. Other thing i think it would be best to change, is that products and values (per item and totals) should have the "no tax" or "tax not included" tag, instead of the "tax included" or "vat included" tag, because this second option is confusing for the client. Of course several languages must have same type of tags. 

I hope i helped. It's really a very good module, but i think that with this modifications it will be extraordinary!

Kind Regards

**Comment by NKoonen** [comment] 2020-11-27 13:13
Duplicate of: https://github.com/NKoonen/vatchecker/issues/2

**Closed by NKoonen** 2020-11-27 13:13 UTC
Labels: duplicate
