### ISSUE TITLE
seems the vies is tested in the same country

### ISSUE THREAD

**Issue by HartLarsson** [NKoonen/vatchecker#27] opened 2023-01-24 15:15 UTC
i've do a test using italy as country and inserting a NON views but good VAT code and seems the VIES is checked.

![image](https://user-images.githubusercontent.com/16102074/214332303-1d34c073-4a55-4489-840c-f28dfef23940.png)

VAT code in the same country must not be checked by default.

this is the config

![image](https://user-images.githubusercontent.com/16102074/214332590-df703298-e560-4ac6-9a84-702f582c6632.png)

if i disable the VIES check

![image](https://user-images.githubusercontent.com/16102074/214335392-73f0d0da-602b-4401-a358-19eb92cf3885.png)

seems it check vies anyway giving error??

![image](https://user-images.githubusercontent.com/16102074/214335541-7e44ec87-4abd-4760-8b83-bd847d2ae3b3.png)

If VIES chekc is OFF why give that error?
Plus the offline validation, because was active, must passing the VIES check anyway.

**Comment by NKoonen** [comment] 2023-01-25 11:52
The "Origin Country" is the country where you can not delivery with 0% tax to.
So what you are describing is not a bug, but a feature. Some companies only do B2B so they require a vat number before sales. If you don't want the vat numbers to be checked in Italy you should disable Italy in the module config.

The error "EU VIES server not responding" could mean three things.
- The EU vies database server is offline
- Your hosting server firewall blocks requests to the VIES database
- You've reached the maximum amount of VIES database request for this hour

**Comment by HartLarsson** [comment] 2023-01-30 18:53
so to avoid VIes check on Italian Wat i neet to unckeck Italy from the list?

**Closed** 2023-01-31 11:28 UTC
